# Generated by Django 4.2.4 on 2024-09-15 05:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('buildingid', models.AutoField(primary_key=True, serialize=False)),
                ('zip_code', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('street', models.CharField(blank=True, max_length=75, null=True)),
                ('city', models.CharField(default='None', max_length=75)),
                ('province', models.CharField(default='None', max_length=75)),
                ('country', models.CharField(default='None', max_length=75)),
                ('details', models.TextField(blank=True, null=True)),
                ('rooms_vacant', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('middlename', models.CharField(max_length=20)),
                ('birthdate', models.DateField(default=django.utils.timezone.now)),
                ('user_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('buildingid', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=250)),
                ('person_free', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('current_male', models.IntegerField(default=0)),
                ('current_female', models.IntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=100)),
                ('room_size', models.CharField(max_length=20)),
                ('shower', models.BooleanField(default=False)),
                ('priv_bathrooom', models.BooleanField(default=False)),
                ('public_bathroom', models.BooleanField(default=False)),
                ('AC', models.BooleanField(default=False)),
                ('wardrobe', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('bedroom', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('double_deck', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('free_wifi', models.BooleanField(default=False)),
                ('building_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='RentScout.building')),
            ],
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('policy', models.TextField(blank=True, default='', null=True)),
                ('buildingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentScout.building')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackid', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('0', '0')], default='0', max_length=10)),
                ('message', models.TextField(default='')),
                ('baordingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentScout.building')),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('facil_id', models.AutoField(primary_key=True, serialize=False)),
                ('free_wifi', models.BooleanField(default=False)),
                ('shared_kitchen', models.BooleanField(default=False)),
                ('smoke_free', models.BooleanField(default=False)),
                ('janitor', models.BooleanField(default=False)),
                ('waterbill', models.BooleanField(default=False)),
                ('electricbill', models.BooleanField(default=False)),
                ('comfort_room', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('buildingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentScout.building')),
            ],
        ),
    ]
