# Generated by Django 4.2.4 on 2024-10-08 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
