# Generated by Django 4.2.4 on 2024-11-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
        migrations.CreateModel(
            name='BuildingReports',
            fields=[
                ('reportid', models.AutoField(primary_key=True, serialize=False)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='', max_length=250)),
                ('buildingid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='building_reported', to='RentScout.building')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reporting_user', to='RentScout.scoutuser')),
            ],
        ),
    ]
