# Generated by Django 4.2.4 on 2025-01-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentid', models.PositiveIntegerField()),
                ('referralid', models.CharField(default='', max_length=60)),
                ('building_name', models.CharField(default='', max_length=250)),
                ('boarder_name', models.CharField(default='', max_length=250)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportid', models.PositiveIntegerField()),
                ('building', models.CharField(default='', max_length=60)),
                ('reporter', models.CharField(default='', max_length=50)),
                ('reason', models.CharField(default='', max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificationid', models.PositiveIntegerField()),
                ('building', models.CharField(default='', max_length=60)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreatedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentid', models.PositiveIntegerField()),
                ('referralid', models.CharField(default='', max_length=60)),
                ('building_name', models.CharField(default='', max_length=250)),
                ('boarder_name', models.CharField(default='', max_length=250)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreatedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportid', models.PositiveIntegerField()),
                ('building', models.CharField(default='', max_length=60)),
                ('reporter', models.CharField(default='', max_length=50)),
                ('reason', models.CharField(default='', max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreatedVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificationid', models.PositiveIntegerField()),
                ('building', models.CharField(default='', max_length=60)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificationid', models.PositiveIntegerField()),
                ('building', models.CharField(default='', max_length=60)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeniedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentid', models.PositiveIntegerField()),
                ('referralid', models.CharField(default='', max_length=60)),
                ('building_name', models.CharField(default='', max_length=50)),
                ('boarder_name', models.CharField(default='', max_length=50)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeniedVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificationid', models.PositiveIntegerField()),
                ('building', models.CharField(default='', max_length=60)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
