# Generated by Django 4.2.4 on 2024-10-31 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['-average_rating']},
        ),
        migrations.AddField(
            model_name='building',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='boardingid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_rating', to='RentScout.building'),
        ),
    ]
