# Generated by Django 4.2.4 on 2024-09-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='baordingid',
            new_name='boardingid',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='buildingid',
            new_name='roomid',
        ),
    ]
