# Generated by Django 4.2.4 on 2024-10-27 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0002_alter_building_building_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='priv_bathrooom',
            new_name='priv_bathroom',
        ),
    ]
