# Generated by Django 4.2.4 on 2025-01-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0002_acceptedpayment_acceptedreport_acceptedverification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeniedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportid', models.PositiveIntegerField()),
                ('building', models.CharField(default='', max_length=60)),
                ('reporter', models.CharField(default='', max_length=50)),
                ('reason', models.CharField(default='', max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
