# Generated by Django 4.2.4 on 2025-01-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0003_deniedreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_image',
            field=models.FileField(blank=True, default='upload/building_imgs/no-image.png', null=True, upload_to='upload/building_imgs'),
        ),
        migrations.AlterField(
            model_name='building',
            name='gcash_qr',
            field=models.FileField(blank=True, default='upload/building_imgs/gcash/no-image.png', null=True, upload_to='upload/building_imgs/gcash'),
        ),
    ]
