# Generated by Django 4.2.4 on 2024-10-29 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0003_rename_priv_bathrooom_room_priv_bathroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutuser_landlord',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ScoutUserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoutuser_bookmark_building', to='RentScout.building')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoutuser_bookmark_owner', to='RentScout.scoutuser')),
            ],
        ),
        migrations.CreateModel(
            name='LandlordUserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_bookmark_building', to='RentScout.building')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_bookmark_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
