# Generated by Django 4.2.4 on 2024-09-19 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0003_building_building_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('highlights_id', models.AutoField(primary_key=True, serialize=False)),
                ('free_wifi', models.BooleanField(default=False)),
                ('shared_kitchen', models.BooleanField(default=False)),
                ('smoke_free', models.BooleanField(default=False)),
                ('janitor', models.BooleanField(default=False)),
                ('guard', models.BooleanField(default=False)),
                ('waterbill', models.BooleanField(default=False)),
                ('electricbill', models.BooleanField(default=False)),
                ('comfort_room', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('buildingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentScout.building')),
            ],
        ),
        migrations.DeleteModel(
            name='Facilities',
        ),
    ]
