# Generated by Django 4.2.4 on 2024-10-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0004_alter_roomimage_room_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='coordinates',
            field=models.CharField(default='', max_length=255),
        ),
    ]
