# Generated by Django 4.2.4 on 2024-11-07 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0004_alter_buildingreport_buildingid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('verificationid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Not Verified', 'Not Verified'), ('Pending', 'Pending'), ('Verified', 'Verified')], default='Not Verified', max_length=15)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('buildingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify_building', to='RentScout.building')),
            ],
        ),
    ]
