# Generated by Django 4.2.4 on 2025-01-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0004_alter_building_building_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoutuser_landlord',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
