# Generated by Django 4.2.4 on 2024-09-19 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0004_highlights_delete_facilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bedroom',
            new_name='bed',
        ),
        migrations.RemoveField(
            model_name='highlights',
            name='comfort_room',
        ),
    ]
