# Generated by Django 4.2.4 on 2025-01-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0005_scoutuser_verified_scoutuser_landlord_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='userid',
            new_name='adminid',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='userid',
            new_name='scoutuserid',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='userid',
            new_name='scoutuserid',
        ),
        migrations.RenameField(
            model_name='scoutuser',
            old_name='userid',
            new_name='scoutuserid',
        ),
        migrations.RenameField(
            model_name='scoutuser_landlord',
            old_name='userid',
            new_name='landlordid',
        ),
    ]
