# Generated by Django 4.2.4 on 2024-11-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0005_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='deny_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
