# Generated by Django 4.2.4 on 2024-10-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0005_building_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutuser',
            name='barangay',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scoutuser',
            name='city',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scoutuser',
            name='contact',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='scoutuser',
            name='province',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
