# Generated by Django 4.2.4 on 2024-11-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0006_verification_deny_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingreport',
            options={'ordering': ['buildingid__average_rating']},
        ),
        migrations.AlterModelOptions(
            name='landlorduserbookmark',
            options={'ordering': ['buildingid__average_rating']},
        ),
        migrations.AddField(
            model_name='scoutuser',
            name='usertype',
            field=models.CharField(default='Boarder', max_length=10),
        ),
        migrations.AddField(
            model_name='scoutuser_landlord',
            name='usertype',
            field=models.CharField(default='Landlord', max_length=10),
        ),
    ]
