# Generated by Django 4.2.4 on 2024-11-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0007_alter_buildingreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutuser_landlord',
            name='gcash',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
