# Generated by Django 4.2.4 on 2024-12-02 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0008_scoutuser_landlord_gcash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=10)),
                ('buildingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_building', to='RentScout.building')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_customer', to='RentScout.scoutuser')),
            ],
        ),
    ]
