# Generated by Django 4.2.4 on 2024-12-03 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0009_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
