# Generated by Django 4.2.4 on 2024-12-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0010_reservation_created_reservation_last_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['created', 'last_updated']},
        ),
    ]
