# Generated by Django 4.2.4 on 2024-12-04 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0011_alter_reservation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='buildingid',
        ),
        migrations.AddField(
            model_name='reservation',
            name='roomid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_room', to='RentScout.room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=10),
        ),
    ]
