# Generated by Django 4.2.4 on 2024-12-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0012_remove_reservation_buildingid_reservation_roomid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='building_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_of_building', to='RentScout.building'),
        ),
    ]
