# Generated by Django 4.2.4 on 2024-12-07 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0013_alter_room_building_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created', '-last_updated']},
        ),
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.AddField(
            model_name='building',
            name='price',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='person_free',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
