# Generated by Django 4.2.4 on 2024-12-07 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0014_alter_reservation_options_remove_room_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='gcash_qr',
            field=models.FileField(blank=True, null=True, upload_to='upload/building_imgs/gcash'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificationid', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_name', models.CharField(default='Certificate', max_length=100)),
                ('image', models.FileField(upload_to='upload/building_imgs/certifications')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('buildingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='RentScout.building')),
            ],
        ),
    ]
