# Generated by Django 4.2.4 on 2024-12-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0016_scoutuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='upload/message'),
        ),
    ]
