# Generated by Django 4.2.4 on 2024-12-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0018_remove_scoutuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutuser',
            name='profile_image',
            field=models.FileField(blank=True, default='user_profiles/user.png', null=True, upload_to='upload/user_profiles'),
        ),
        migrations.AddField(
            model_name='scoutuser_landlord',
            name='profile_image',
            field=models.FileField(blank=True, default='user_profiles/user.png', null=True, upload_to='upload/user_profiles'),
        ),
    ]
