# Generated by Django 4.2.4 on 2024-12-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0019_scoutuser_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoutuser',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='scoutuser_landlord',
            name='profile_image',
        ),
    ]
