# Generated by Django 4.2.4 on 2024-12-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0021_scoutuser_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='border',
            new_name='boarder',
        ),
    ]
