# Generated by Django 4.2.4 on 2024-12-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0022_rename_border_message_boarder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(default='', null=True),
        ),
    ]
