# Generated by Django 4.2.4 on 2025-01-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentScout', '0025_alter_reservation_roomid_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Hidden', 'Hidden')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Payed', 'Payed')], default='Pending', max_length=10),
        ),
    ]
